// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sms_warehouse

import (
	"database/sql"
)

type SmsWarehouse struct {
	ID                  int64
	ReceiverPhoneNumber string
	Message             string
	Status              int64
	CreatedAt           string
	UpdatedAt           string
	DeletedAt           sql.NullString
}
