// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package sms_warehouse

import (
	"context"
)

const createSMSWarehouseRecord = `-- name: CreateSMSWarehouseRecord :one
INSERT INTO sms_warehouse (
    receiver_phone_number,
    message,
    status
) VALUES (
    ?, ?, ?
) RETURNING id, receiver_phone_number, message, status, created_at, updated_at, deleted_at
`

type CreateSMSWarehouseRecordParams struct {
	ReceiverPhoneNumber string
	Message             string
	Status              int64
}

func (q *Queries) CreateSMSWarehouseRecord(ctx context.Context, arg CreateSMSWarehouseRecordParams) (SmsWarehouse, error) {
	row := q.db.QueryRowContext(ctx, createSMSWarehouseRecord, arg.ReceiverPhoneNumber, arg.Message, arg.Status)
	var i SmsWarehouse
	err := row.Scan(
		&i.ID,
		&i.ReceiverPhoneNumber,
		&i.Message,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getPendingSMSWarehouseRecords = `-- name: GetPendingSMSWarehouseRecords :many
SELECT id, receiver_phone_number, message, status, created_at, updated_at, deleted_at FROM sms_warehouse
WHERE status = 0 AND deleted_at IS NULL
ORDER BY id ASC
`

func (q *Queries) GetPendingSMSWarehouseRecords(ctx context.Context) ([]SmsWarehouse, error) {
	rows, err := q.db.QueryContext(ctx, getPendingSMSWarehouseRecords)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SmsWarehouse
	for rows.Next() {
		var i SmsWarehouse
		if err := rows.Scan(
			&i.ID,
			&i.ReceiverPhoneNumber,
			&i.Message,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSMSWarehouseByID = `-- name: GetSMSWarehouseByID :one
SELECT id, receiver_phone_number, message, status, created_at, updated_at, deleted_at FROM sms_warehouse
WHERE id = ? AND deleted_at IS NULL
`

func (q *Queries) GetSMSWarehouseByID(ctx context.Context, id int64) (SmsWarehouse, error) {
	row := q.db.QueryRowContext(ctx, getSMSWarehouseByID, id)
	var i SmsWarehouse
	err := row.Scan(
		&i.ID,
		&i.ReceiverPhoneNumber,
		&i.Message,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const updateSMSWarehouseStatus = `-- name: UpdateSMSWarehouseStatus :exec
UPDATE sms_warehouse
SET status = ?,
    updated_at = datetime('now')
WHERE id = ? AND deleted_at IS NULL
`

type UpdateSMSWarehouseStatusParams struct {
	Status int64
	ID     int64
}

func (q *Queries) UpdateSMSWarehouseStatus(ctx context.Context, arg UpdateSMSWarehouseStatusParams) error {
	_, err := q.db.ExecContext(ctx, updateSMSWarehouseStatus, arg.Status, arg.ID)
	return err
}
