app:
  port: 8080 # Application HTTP port (used when starting the program)
  max_json_request_size: 1024 # maximum json request size
  max_upload_files_size: 8196 # maximum upload file size

cors:
  allow_origins:
    - "http://localhost:4200"

    # Fixed ports you already have
    - "http://192.168.1.2:80"
    - "http://192.168.1.2:81"
    - "http://192.168.1.2:82"
    - "http://192.168.1.2:83"
    - "http://192.168.1.2:84"
    - "http://192.168.1.2:85"
    - "http://192.168.1.2:86"
    - "http://192.168.1.2:87"
    - "http://192.168.1.2:88"
    - "http://192.168.1.2:89"
    - "http://192.168.1.2:90"

    # Range 192.168.1.3–192.168.1.30 on port 4200
    - "http://192.168.1.3:4200"
    - "http://192.168.1.4:4200"
    - "http://192.168.1.5:4200"
    - "http://192.168.1.6:4200"
    - "http://192.168.1.7:4200"
    - "http://192.168.1.8:4200"
    - "http://192.168.1.9:4200"
    - "http://192.168.1.10:4200"
    - "http://192.168.1.11:4200"
    - "http://192.168.1.12:4200"
    - "http://192.168.1.13:4200"
    - "http://192.168.1.14:4200"
    - "http://192.168.1.15:4200"
    - "http://192.168.1.16:4200"
    - "http://192.168.1.17:4200"
    - "http://192.168.1.18:4200"
    - "http://192.168.1.19:4200"
    - "http://192.168.1.20:4200"
    - "http://192.168.1.21:4200"
    - "http://192.168.1.22:4200"
    - "http://192.168.1.23:4200"
    - "http://192.168.1.24:4200"
    - "http://192.168.1.25:4200"
    - "http://192.168.1.26:4200"
    - "http://192.168.1.27:4200"
    - "http://192.168.1.28:4200"
    - "http://192.168.1.29:4200"
    - "http://192.168.1.30:4200"

  allow_methods:
    - "GET"
    - "POST"
    - "PUT"
    - "DELETE"
    - "OPTIONS"

  allow_headers:
    - "Content-Type"
    - "Authorization"
    - "x-api-key"

  expose_headers:
    - "Content-Length"

  allow_credentials: true
  max_age_hours: 12 # 12 hours

captcha:
  length: 6 # Number of characters in the captcha
  timeout_minutes: 5 # Captcha lifetime (in-memory cache TTL, minutes)
  expired_time_token: 15 # Captcha JWT token TTL (minutes)
  cookie_name: "captcha_token" # Cookie name for storing captcha JWT token
  cleanup_interval: 10 # Cleanup interval for expired captchas (minutes)
  max_cashed_captcha: 100000 # Max number of captchas stored in cache
  image_width: 240 # Captcha image width in pixels
  image_height: 80 # Captcha image height in pixels
  validate_ip: true

token:
  httponly: true # Use HttpOnly flag for cookies (recommended true)
  secure: false # Use Secure flag for cookies (true if HTTPS)

one_time_token:
  cleanup_interval: 10 # Cleanup interval for expired one-time tokens (minutes)
  max_cashed_tokens: 100000 # Max number of one-time tokens stored in cache
  expired_time_token: 3 # One-time JWT token TTL (minutes)

auth:
  expired_time_token: 60 # Auth JWT token TTL (minutes)
  cookie_name: "auth_token" # Cookie name for auth JWT token

mongo:
  enable: true # Enable MongoDB integration
  db_name: "ticket_db" # MongoDB database name
  ticket_collocation_name: "tickets" # Collection name for tickets

redis:
  enable: true # Enable Redis integration
  host: "localhost" # Redis host
  port: 6379 # Redis port
  db: 0 # Redis logical database (integer 0 - 15)

cache:
  ticket_type_ttl_minutes: 1440 # TTL for ticket types cache
  department_ttl_minutes: 1440 # TTL for department cache
  ticket_status_ttl_minutes: 1440 # TTL for ticket status cache

minio:
  enable: true
  host: "localhost"
  bucket: "ticket-files"
  port: 9000
  use_ssl: false

upload:
  size: 1024 // size KB

ticket:
  # The maximum number of items a client can request per page.
  # Any request asking for more than this will use default_paging_size.
  max_paging_size: 100

  # The default number of items per page if the client does not specify a limit,
  # or if the requested limit is larger than max_paging_size.
  default_paging_size: 10

  # The minimum number of items allowed per page.
  # Requests below this size will also use default_paging_size.
  min_paging_size: 2

  # The maximum number of items that can be counted or processed in bulk.
  # Useful to prevent slow queries on large collections.
  max_counting_item: 10000

  # maximum count file can user upload per ticket
  max_ticket_upload_file: 3

  # maximum size kb ticket upload file
  max_ticket_upload_file_size: 1024 # 1MB

  acceptable_files_for_upload:
    - .jpg
    - .jpeg
    - .png

api_key:
  size: 32 # API Key size in bytes
