// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package ticket_priorities

import (
	"database/sql"
)

type TicketPriority struct {
	UserID       int64
	TicketTypeID int64
	Priority     int64
	CreatedAt    string
	UpdatedAt    string
	DeletedAt    sql.NullString
	Status       int64
}
