// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package ticket_priorities

type TicketPriority struct {
	UserID       int64
	TicketTypeID int64
	Priority     int64
	Status       int64
	Deleted      int64
}
