// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package ticket_priorities

import (
	"context"
)

const addTicketPriority = `-- name: AddTicketPriority :exec
INSERT INTO ticket_priorities (user_id, ticket_type_id, priority) VALUES (?, ?, ?)
`

type AddTicketPriorityParams struct {
	UserID       int64
	TicketTypeID int64
	Priority     int64
}

func (q *Queries) AddTicketPriority(ctx context.Context, arg AddTicketPriorityParams) error {
	_, err := q.db.ExecContext(ctx, addTicketPriority, arg.UserID, arg.TicketTypeID, arg.Priority)
	return err
}
