// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package roles

import (
	"database/sql"
)

type Role struct {
	ID        int64
	Title     string
	Status    int64
	Deleted   int64
	CreatedAt string
	UpdatedAt string
	DeletedAt sql.NullString
}
