// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package ticket_statuses

import (
	"database/sql"
)

type TicketStatus struct {
	ID          int64
	Title       string
	Description sql.NullString
	Status      int64
	Deleted     int64
}
