// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package api_handlers

import (
	"database/sql"
)

type ApiHandler struct {
	ID          int64
	Handler     string
	Method      string
	Description sql.NullString
	Status      int64
	Deleted     int64
}
