// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package api_handlers

import (
	"context"
	"database/sql"
)

const addApiHandler = `-- name: AddApiHandler :one
INSERT INTO api_handlers (handler, method, description) VALUES (?, ?, ?) RETURNING id
`

type AddApiHandlerParams struct {
	Handler     string
	Method      string
	Description sql.NullString
}

func (q *Queries) AddApiHandler(ctx context.Context, arg AddApiHandlerParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, addApiHandler, arg.Handler, arg.Method, arg.Description)
	var id int64
	err := row.Scan(&id)
	return id, err
}
