// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sms_messages

import (
	"database/sql"
)

type SmsMessage struct {
	ID          int64
	Title       string
	Body        string
	Description sql.NullString
	CreatedAt   string
	UpdatedAt   string
	DeletedAt   sql.NullString
}
