// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package sms_messages

import (
	"context"
)

const getAllSMSMessages = `-- name: GetAllSMSMessages :many
SELECT id, title, body, description, created_at, updated_at, deleted_at FROM sms_messages
WHERE deleted_at IS NULL
ORDER BY id ASC
`

func (q *Queries) GetAllSMSMessages(ctx context.Context) ([]SmsMessage, error) {
	rows, err := q.db.QueryContext(ctx, getAllSMSMessages)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SmsMessage
	for rows.Next() {
		var i SmsMessage
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Body,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSMSMessageByID = `-- name: GetSMSMessageByID :one
SELECT id, title, body, description, created_at, updated_at, deleted_at FROM sms_messages
WHERE id = ? AND deleted_at IS NULL
`

func (q *Queries) GetSMSMessageByID(ctx context.Context, id int64) (SmsMessage, error) {
	row := q.db.QueryRowContext(ctx, getSMSMessageByID, id)
	var i SmsMessage
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Body,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
