// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package permissions

import (
	"database/sql"
)

type Permission struct {
	ID          int64
	Name        string
	Description sql.NullString
	Status      int64
	CreatedAt   string
	UpdatedAt   string
	DeletedAt   sql.NullString
}
