// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package permissions

import (
	"context"
	"database/sql"
)

const addPermission = `-- name: AddPermission :one
INSERT INTO permissions (name, description)
VALUES (?, ?)
RETURNING id
`

type AddPermissionParams struct {
	Name        string
	Description sql.NullString
}

func (q *Queries) AddPermission(ctx context.Context, arg AddPermissionParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, addPermission, arg.Name, arg.Description)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const getAllActivePermissions = `-- name: GetAllActivePermissions :many
SELECT id, name, description, status, created_at, updated_at
FROM permissions
WHERE deleted_at IS NULL
AND status != 0
`

type GetAllActivePermissionsRow struct {
	ID          int64
	Name        string
	Description sql.NullString
	Status      int64
	CreatedAt   string
	UpdatedAt   string
}

func (q *Queries) GetAllActivePermissions(ctx context.Context) ([]GetAllActivePermissionsRow, error) {
	rows, err := q.db.QueryContext(ctx, getAllActivePermissions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAllActivePermissionsRow
	for rows.Next() {
		var i GetAllActivePermissionsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPermissionByName = `-- name: GetPermissionByName :one
SELECT id, name, description, status, created_at, updated_at
FROM permissions
WHERE deleted_at IS NULL
AND status != 0
AND name = ?
`

type GetPermissionByNameRow struct {
	ID          int64
	Name        string
	Description sql.NullString
	Status      int64
	CreatedAt   string
	UpdatedAt   string
}

func (q *Queries) GetPermissionByName(ctx context.Context, name string) (GetPermissionByNameRow, error) {
	row := q.db.QueryRowContext(ctx, getPermissionByName, name)
	var i GetPermissionByNameRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
