// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sms_type_messages_relation

import (
	"database/sql"
)

type SmsMessage struct {
	ID          int64
	Title       string
	Body        string
	Description sql.NullString
	CreatedAt   string
	UpdatedAt   string
	DeletedAt   sql.NullString
}

type SmsType struct {
	ID          int64
	Title       string
	Description sql.NullString
	CreatedAt   string
	UpdatedAt   string
	DeletedAt   sql.NullString
}

type SmsTypeMessagesRelation struct {
	ID           int64
	SmsTypeID    int64
	SmsMessageID int64
	CreatedAt    string
	UpdatedAt    string
	DeletedAt    sql.NullString
}
