// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package sms_type_messages_relation

import (
	"context"
)

const getAllSMSTypeMessageRelations = `-- name: GetAllSMSTypeMessageRelations :many
SELECT
    st.id AS sms_type_id,
    st.title AS sms_type_title,
    sm.id AS sms_message_id,
    sm.title AS sms_message_title,
    sm.body AS sms_message_body
FROM sms_type_messages_relation stmr
INNER JOIN sms_types st ON st.id = stmr.sms_type_id AND st.deleted_at IS NULL
INNER JOIN sms_messages sm ON sm.id = stmr.sms_message_id AND sm.deleted_at IS NULL
WHERE stmr.deleted_at IS NULL
`

type GetAllSMSTypeMessageRelationsRow struct {
	SmsTypeID       int64
	SmsTypeTitle    string
	SmsMessageID    int64
	SmsMessageTitle string
	SmsMessageBody  string
}

func (q *Queries) GetAllSMSTypeMessageRelations(ctx context.Context) ([]GetAllSMSTypeMessageRelationsRow, error) {
	rows, err := q.db.QueryContext(ctx, getAllSMSTypeMessageRelations)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAllSMSTypeMessageRelationsRow
	for rows.Next() {
		var i GetAllSMSTypeMessageRelationsRow
		if err := rows.Scan(
			&i.SmsTypeID,
			&i.SmsTypeTitle,
			&i.SmsMessageID,
			&i.SmsMessageTitle,
			&i.SmsMessageBody,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getMessageBySMSTypeTitle = `-- name: GetMessageBySMSTypeTitle :one
SELECT
    sm.body
FROM sms_type_messages_relation stmr
INNER JOIN sms_types st ON st.id = stmr.sms_type_id AND st.deleted_at IS NULL
INNER JOIN sms_messages sm ON sm.id = stmr.sms_message_id AND sm.deleted_at IS NULL
WHERE st.title = ? AND stmr.deleted_at IS NULL
LIMIT 1
`

func (q *Queries) GetMessageBySMSTypeTitle(ctx context.Context, title string) (string, error) {
	row := q.db.QueryRowContext(ctx, getMessageBySMSTypeTitle, title)
	var body string
	err := row.Scan(&body)
	return body, err
}
