// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package version

import (
	"database/sql"
)

type AppVersion struct {
	ID          int64
	ApiVersion  string
	Version     string
	ReleaseDate string
	Notes       sql.NullString
	IsCurrent   int64
}
