// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package api_routes

import (
	"database/sql"
)

type ApiRoute struct {
	ID          int64
	Route       string
	Method      string
	Description sql.NullString
	Status      int64
	Deleted     int64
}
