// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package api_keys

import (
	"database/sql"
)

type ApiKey struct {
	ID          int64
	Key         string
	Description sql.NullString
	CreatedAt   string
	UpdatedAt   string
	DeletedAt   sql.NullString
	Status      int64
}
