// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package roles_relations

type ApiKeysRolesRelation struct {
	ApiKeyID int64
	RoleID   int64
	Status   int64
	Deleted  int64
}

type ApiRoutesRolesRelation struct {
	ApiRouteID int64
	RoleID     int64
	Status     int64
	Deleted    int64
}

type TicketTypesRolesRelation struct {
	TicketTypeID int64
	RoleID       int64
	Status       int64
	Deleted      int64
}

type UsersRolesRelation struct {
	UserID  int64
	RoleID  int64
	Status  int64
	Deleted int64
}
