// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package roles_relations

type ApiHandlersRolesRelation struct {
	ApiHandlerID int64
	RoleID       int64
	Status       int64
	Deleted      int64
}

type TicketTypesRolesRelation struct {
	TicketTypeID int64
	RoleID       int64
	Status       int64
	Deleted      int64
}

type UsersRolesRelation struct {
	UserID  int64
	RoleID  int64
	Status  int64
	Deleted int64
}
