// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/auth/CheckToken/": {
            "get": {
                "description": "Inspects session cookies (auth_token, captcha_token) without triggering 401 unauthenticated errors. Returns token metadata and phone verification state.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Check token validation status",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.CheckTokenResponseDTO"
                        }
                    }
                }
            }
        },
        "/auth/GetSingleUseToken/": {
            "post": {
                "description": "Returns a one-time JWT token to authenticate on another service",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Generate one-time token for a user",
                "parameters": [
                    {
                        "description": "Username",
                        "name": "payload",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.GenerateSingleUseTokenDTO"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.SingleUseTokenResponseDTO"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/errx.APIError"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/errx.APIError"
                        }
                    }
                }
            }
        },
        "/auth/Login/": {
            "post": {
                "description": "Authenticate user and set secure auth cookie",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Login with username and password",
                "parameters": [
                    {
                        "description": "Login credentials",
                        "name": "payload",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.LoginWithPasswordDTO"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/errx.APIError"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/errx.APIError"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/errx.APIError"
                        }
                    }
                }
            }
        },
        "/auth/LoginWithNoAuth/": {
            "post": {
                "description": "If a user with the provided username and department ID exists, it returns the user's ID. Otherwise, it creates a new user and returns the new ID.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Auth"
                ],
                "summary": "Login or create user without authentication",
                "parameters": [
                    {
                        "description": "Login data",
                        "name": "login",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.LoginWitNoAuthDTO"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "User found and ID returned",
                        "schema": {
                            "$ref": "#/definitions/dto.IDResponseInt64"
                        }
                    },
                    "201": {
                        "description": "New user created and ID returned",
                        "schema": {
                            "$ref": "#/definitions/dto.IDResponseInt64"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/errx.APIError"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/errx.APIError"
                        }
                    }
                }
            }
        },
        "/auth/LoginWithSingleUseToken/": {
            "get": {
                "description": "Validates a SingleUse token and returns an auth JWT",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Login using a SingleUse token",
                "parameters": [
                    {
                        "type": "string",
                        "description": "SingleUse token",
                        "name": "token",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/errx.APIError"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/errx.APIError"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/errx.APIError"
                        }
                    }
                }
            }
        },
        "/auth/SignUp/": {
            "post": {
                "description": "Create a new user with username and password",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Sign up with username and password",
                "parameters": [
                    {
                        "description": "Signup credentials",
                        "name": "payload",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.SignUpWithPasswordDTO"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/dto.IDResponseInt64"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/errx.APIError"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/errx.APIError"
                        }
                    }
                }
            }
        },
        "/captcha/GetCaptcha/": {
            "get": {
                "description": "Generates a new captcha and returns its ID and image (base64)",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Captcha"
                ],
                "summary": "Generate new captcha",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.CaptchaResultDTO"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/errx.Error"
                        }
                    }
                }
            }
        },
        "/captcha/VerifyCaptcha/": {
            "post": {
                "description": "Verifies the captcha ID and user-provided answer",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Captcha"
                ],
                "summary": "Verify captcha",
                "parameters": [
                    {
                        "description": "Captcha Request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.CaptchaVerifyRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.CaptchaVerifyRequest"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/errx.Error"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/errx.Error"
                        }
                    }
                }
            }
        },
        "/departments/GetAllActiveDepartments/": {
            "get": {
                "description": "Returns a list of all active departments",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Department"
                ],
                "summary": "Get all active departments",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/dto.DepartmentDTO"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/errx.APIError"
                        }
                    }
                }
            }
        },
        "/files/GetDownloadLinkTicketFile/{objectName}/": {
            "post": {
                "description": "Generates a temporary presigned URL for the given file and redirects the client to that URL to start the download.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "TicketFile"
                ],
                "summary": "Download a ticket file",
                "parameters": [
                    {
                        "type": "string",
                        "description": "File object name (UUID + extension)",
                        "name": "objectName",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "ticket ID for file location",
                        "name": "ticketId",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.IDRequestString"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Give MinIO download URL"
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/errx.APIError"
                        }
                    },
                    "404": {
                        "description": "File not found",
                        "schema": {
                            "$ref": "#/definitions/errx.APIError"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/errx.APIError"
                        }
                    }
                }
            }
        },
        "/files/UploadTicketFile/": {
            "post": {
                "description": "Upload a file to the temporary storage for a ticket. File must be multipart/form-data with field name ` + "`" + `file` + "`" + `.",
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "TicketFile"
                ],
                "summary": "Upload a ticket file",
                "parameters": [
                    {
                        "type": "file",
                        "description": "Ticket file to upload",
                        "name": "file",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Returns uploaded file ID",
                        "schema": {
                            "$ref": "#/definitions/dto.IDResponseString"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/errx.APIError"
                        }
                    },
                    "413": {
                        "description": "File too large",
                        "schema": {
                            "$ref": "#/definitions/errx.APIError"
                        }
                    },
                    "415": {
                        "description": "Unsupported file extension",
                        "schema": {
                            "$ref": "#/definitions/errx.APIError"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/errx.APIError"
                        }
                    }
                }
            }
        },
        "/otp/send": {
            "post": {
                "description": "Generates a verification code, caches in Redis, logs to SMS warehouse, and sends SMS via provider asynchronously",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "OTP"
                ],
                "summary": "Send OTP verification code",
                "parameters": [
                    {
                        "description": "Phone number",
                        "name": "payload",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.SendOTPDTO"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Verification code sent",
                        "schema": {
                            "$ref": "#/definitions/dto.SendOTPResponseDTO"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/errx.APIError"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/errx.APIError"
                        }
                    }
                }
            }
        },
        "/otp/verify": {
            "post": {
                "description": "Validates provided OTP code against cached code in Redis",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "OTP"
                ],
                "summary": "Verify OTP code",
                "parameters": [
                    {
                        "description": "Phone number and OTP code",
                        "name": "payload",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.VerifyOTPDTO"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OTP is valid",
                        "schema": {
                            "$ref": "#/definitions/dto.VerifyOTPResponseDTO"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/errx.APIError"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/errx.APIError"
                        }
                    }
                }
            }
        },
        "/tickets/CloseTicket/": {
            "post": {
                "description": "Closes ticket by setting status to close",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Ticket"
                ],
                "summary": "Close ticket by ID",
                "parameters": [
                    {
                        "description": "Ticket ID",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.IDRequestString"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.TicketResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/errx.APIError"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/errx.APIError"
                        }
                    }
                }
            }
        },
        "/tickets/CreateTicket/": {
            "post": {
                "description": "Creates a new ticket with the provided data",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Ticket"
                ],
                "summary": "Create a new ticket",
                "parameters": [
                    {
                        "description": "Ticket data",
                        "name": "ticket",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.TicketCreateRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/dto.TicketCreateResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/errx.APIError"
                        }
                    },
                    "409": {
                        "description": "Conflict",
                        "schema": {
                            "$ref": "#/definitions/errx.APIError"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/errx.APIError"
                        }
                    }
                }
            }
        },
        "/tickets/GetAllActiveTicketStatuses/": {
            "get": {
                "description": "Returns a list of all active ticket statuses",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Ticket"
                ],
                "summary": "Get all active ticket statuses",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/dto.TicketStatusDTO"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/errx.APIError"
                        }
                    }
                }
            }
        },
        "/tickets/GetAllActiveTicketTypes/": {
            "get": {
                "description": "Returns a list of all active ticket types",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Ticket"
                ],
                "summary": "Get all active ticket types",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/dto.TicketTypeDto"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/errx.APIError"
                        }
                    }
                }
            }
        },
        "/tickets/GetTicketByID/": {
            "post": {
                "description": "Returns a ticket by its ID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Ticket"
                ],
                "summary": "Get ticket by ID",
                "parameters": [
                    {
                        "description": "Ticket ID Request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.TicketByIDRequestDTO"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.TicketResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/errx.APIError"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/errx.APIError"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/errx.APIError"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/errx.APIError"
                        }
                    }
                }
            }
        },
        "/tickets/GetTicketByTrackCode/": {
            "post": {
                "description": "Returns a ticket by its track code",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Ticket"
                ],
                "summary": "Get ticket by track code",
                "parameters": [
                    {
                        "description": "Track Code Request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.TicketByTrackCodeRequestDTO"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.TicketResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/errx.APIError"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/errx.APIError"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/errx.APIError"
                        }
                    }
                }
            }
        },
        "/tickets/GetTicketsList/": {
            "post": {
                "description": "Returns a paginated list of tickets based on complex filter and sort options",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Ticket"
                ],
                "summary": "List tickets with paging and filtering",
                "parameters": [
                    {
                        "description": "Ticket filter and paging options",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.TicketQueryParams"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.TicketPagingResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/errx.APIError"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/errx.APIError"
                        }
                    }
                }
            }
        },
        "/tickets/{id}/CreateChat/": {
            "post": {
                "description": "Adds a new chat message to the specified ticket ID, uploads attachments, and returns the created message.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Chat"
                ],
                "summary": "Create a new chat message for a ticket",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Ticket ID (UUID)",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Chat message payload",
                        "name": "message",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.ChatMessageCreateRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/dto.ChatMessageDTO"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/errx.APIError"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/errx.APIError"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/errx.APIError"
                        }
                    }
                }
            }
        },
        "/users/GetUserByID/": {
            "post": {
                "description": "Returns the requested user",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User"
                ],
                "summary": "Get user by ID",
                "parameters": [
                    {
                        "description": "User ID",
                        "name": "userID",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.IDRequestInt64"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.UserDTO"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/errx.APIError"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/errx.APIError"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/errx.APIError"
                        }
                    }
                }
            }
        },
        "/users/GetUserByUsername/": {
            "post": {
                "description": "Returns the requested user",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User"
                ],
                "summary": "Get user by username",
                "parameters": [
                    {
                        "description": "Username",
                        "name": "username",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.UsernameDTO"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.UserDTO"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/errx.APIError"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/errx.APIError"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/errx.APIError"
                        }
                    }
                }
            }
        },
        "/users/GetUsersByIDs/": {
            "post": {
                "description": "Returns a list of all users requested",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User"
                ],
                "summary": "Get all users by IDs",
                "parameters": [
                    {
                        "description": "Users IDs",
                        "name": "usersIDs",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.UserIDsDTO"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/dto.UserDTO"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/errx.APIError"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/errx.APIError"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/errx.APIError"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "dto.CaptchaResultDTO": {
            "type": "object",
            "properties": {
                "answer": {
                    "description": "optional, only in debug mode",
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "image": {
                    "description": "base64",
                    "type": "string"
                }
            }
        },
        "dto.CaptchaVerifyRequest": {
            "type": "object",
            "required": [
                "captcha",
                "id"
            ],
            "properties": {
                "captcha": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                }
            }
        },
        "dto.ChatMessageCreateRequest": {
            "type": "object",
            "required": [
                "message"
            ],
            "properties": {
                "attachments": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "message": {
                    "type": "string"
                }
            }
        },
        "dto.ChatMessageDTO": {
            "type": "object",
            "properties": {
                "attachments": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "createdAt": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "message": {
                    "type": "string"
                },
                "senderId": {
                    "type": "integer"
                },
                "senderType": {
                    "type": "string"
                },
                "updatedAt": {
                    "type": "string"
                }
            }
        },
        "dto.CheckTokenResponseDTO": {
            "type": "object",
            "properties": {
                "permissions": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "phoneNumber": {
                    "type": "string"
                },
                "phoneVerified": {
                    "type": "boolean"
                },
                "roleIds": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                },
                "tokenType": {
                    "description": "\"auth\" | \"guest\" | \"captcha\" | \"none\"",
                    "type": "string"
                },
                "userId": {
                    "type": "integer"
                },
                "username": {
                    "type": "string"
                },
                "valid": {
                    "type": "boolean"
                }
            }
        },
        "dto.DepartmentDTO": {
            "type": "object",
            "properties": {
                "description": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "title": {
                    "type": "string"
                }
            }
        },
        "dto.GenerateSingleUseTokenDTO": {
            "type": "object",
            "required": [
                "username"
            ],
            "properties": {
                "username": {
                    "type": "string"
                }
            }
        },
        "dto.IDRequestInt64": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "integer"
                }
            }
        },
        "dto.IDRequestString": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "string"
                }
            }
        },
        "dto.IDResponseInt64": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "integer"
                }
            }
        },
        "dto.IDResponseString": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "string"
                }
            }
        },
        "dto.LoginWitNoAuthDTO": {
            "type": "object",
            "required": [
                "departmentId",
                "username"
            ],
            "properties": {
                "departmentId": {
                    "type": "integer"
                },
                "username": {
                    "type": "string"
                }
            }
        },
        "dto.LoginWithPasswordDTO": {
            "type": "object",
            "required": [
                "password",
                "username"
            ],
            "properties": {
                "password": {
                    "type": "string"
                },
                "username": {
                    "type": "string"
                }
            }
        },
        "dto.SendOTPDTO": {
            "type": "object",
            "required": [
                "phoneNumber"
            ],
            "properties": {
                "phoneNumber": {
                    "type": "string"
                }
            }
        },
        "dto.SendOTPResponseDTO": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string"
                }
            }
        },
        "dto.SignUpWithPasswordDTO": {
            "type": "object",
            "required": [
                "departmentId",
                "password",
                "username"
            ],
            "properties": {
                "departmentId": {
                    "type": "integer"
                },
                "password": {
                    "type": "string"
                },
                "username": {
                    "type": "string"
                }
            }
        },
        "dto.SingleUseTokenResponseDTO": {
            "type": "object",
            "properties": {
                "token": {
                    "type": "string"
                }
            }
        },
        "dto.TicketByIDRequestDTO": {
            "type": "object",
            "required": [
                "id"
            ],
            "properties": {
                "id": {
                    "description": "assuming UUID",
                    "type": "string"
                }
            }
        },
        "dto.TicketByTrackCodeRequestDTO": {
            "type": "object",
            "required": [
                "trackCode"
            ],
            "properties": {
                "trackCode": {
                    "type": "string"
                }
            }
        },
        "dto.TicketCreateRequest": {
            "type": "object",
            "required": [
                "body",
                "departmentId",
                "ticketTypeId",
                "title"
            ],
            "properties": {
                "attachments": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "body": {
                    "type": "string"
                },
                "departmentId": {
                    "type": "integer"
                },
                "ticketTypeId": {
                    "type": "integer"
                },
                "title": {
                    "type": "string"
                }
            }
        },
        "dto.TicketCreateResponse": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "string"
                },
                "trackCode": {
                    "type": "string"
                }
            }
        },
        "dto.TicketPagingResponse": {
            "type": "object",
            "properties": {
                "items": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/dto.TicketResponse"
                    }
                },
                "page": {
                    "type": "integer"
                },
                "page_size": {
                    "type": "integer"
                },
                "total": {
                    "type": "integer"
                },
                "total_pages": {
                    "type": "integer"
                }
            }
        },
        "dto.TicketQueryParams": {
            "type": "object",
            "properties": {
                "departmentId": {
                    "type": "integer"
                },
                "orderBy": {
                    "description": "field to order by",
                    "type": "string"
                },
                "orderDir": {
                    "description": "asc or desc",
                    "type": "string"
                },
                "page": {
                    "description": "page number",
                    "type": "integer"
                },
                "pageSize": {
                    "description": "items per page",
                    "type": "integer"
                },
                "ticketStatusId": {
                    "description": "optional filter",
                    "type": "integer"
                },
                "ticketTypeId": {
                    "type": "integer"
                },
                "userId": {
                    "description": "optional filter",
                    "type": "integer"
                }
            }
        },
        "dto.TicketResponse": {
            "type": "object",
            "properties": {
                "chat": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/dto.ChatMessageDTO"
                    }
                },
                "createdAt": {
                    "type": "string"
                },
                "departmentId": {
                    "type": "integer"
                },
                "id": {
                    "type": "string"
                },
                "phoneNumber": {
                    "type": "string"
                },
                "ticketStatusId": {
                    "type": "integer"
                },
                "ticketTypeId": {
                    "type": "integer"
                },
                "title": {
                    "type": "string"
                },
                "trackCode": {
                    "type": "string"
                },
                "updatedAt": {
                    "type": "string"
                },
                "userId": {
                    "type": "integer"
                }
            }
        },
        "dto.TicketStatusDTO": {
            "type": "object",
            "properties": {
                "description": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "title": {
                    "type": "string"
                }
            }
        },
        "dto.TicketTypeDto": {
            "type": "object",
            "properties": {
                "description": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "title": {
                    "type": "string"
                }
            }
        },
        "dto.UserDTO": {
            "type": "object",
            "properties": {
                "createdAt": {
                    "type": "string"
                },
                "departmentId": {
                    "type": "integer"
                },
                "id": {
                    "type": "integer"
                },
                "updatedAt": {
                    "type": "string"
                },
                "username": {
                    "type": "string"
                }
            }
        },
        "dto.UserIDsDTO": {
            "type": "object",
            "required": [
                "ids"
            ],
            "properties": {
                "ids": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                }
            }
        },
        "dto.UsernameDTO": {
            "type": "object",
            "required": [
                "username"
            ],
            "properties": {
                "username": {
                    "type": "string"
                }
            }
        },
        "dto.VerifyOTPDTO": {
            "type": "object",
            "required": [
                "code",
                "phoneNumber"
            ],
            "properties": {
                "code": {
                    "type": "string"
                },
                "phoneNumber": {
                    "type": "string"
                }
            }
        },
        "dto.VerifyOTPResponseDTO": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string"
                },
                "valid": {
                    "type": "boolean"
                }
            }
        },
        "errx.APIError": {
            "type": "object",
            "properties": {
                "error": {
                    "$ref": "#/definitions/errx.Error"
                }
            }
        },
        "errx.Error": {
            "type": "object",
            "properties": {
                "code": {
                    "$ref": "#/definitions/errx.ErrorCode"
                },
                "debug": {
                    "type": "string"
                },
                "message": {
                    "type": "string"
                },
                "stack": {
                    "type": "string"
                }
            }
        },
        "errx.ErrorCode": {
            "type": "integer",
            "enum": [
                0,
                1,
                2,
                3,
                4,
                5,
                6,
                7,
                8,
                9,
                10,
                11,
                12,
                13,
                14,
                15,
                16,
                17,
                18,
                19,
                20,
                21,
                22,
                23,
                24,
                25,
                26,
                27,
                28,
                29
            ],
            "x-enum-varnames": [
                "ErrInternalServerError",
                "ErrTicketNotFound",
                "ErrUnauthorized",
                "ErrInvalidInput",
                "ErrDuplicate",
                "ErrBadRequest",
                "ErrUserNotFound",
                "ErrTicketTypeNotFound",
                "ErrDepartmentNotFound",
                "ErrUserDuplicate",
                "ErrInvalidCredentials",
                "ErrWeakJWTSecret",
                "ErrIncorrectCaptcha",
                "ErrExpiredCaptcha",
                "ErrTicketStatusNotFound",
                "ErrTooManyRequest",
                "ErrApiKeyNotFound",
                "ErrServiceUnavailable",
                "ErrFileNotFound",
                "ErrLinkExpired",
                "ErrUnsupportedFileExtension",
                "ErrMaxFileSizeExceeded",
                "ErrMaxTicketFilesExceeded",
                "ErrRequestBodyTooLarge",
                "ErrForbidden",
                "ErrNotFound",
                "ErrOTPExpired",
                "ErrOTPInvalid",
                "ErrOTPSendFailed",
                "ErrOTPMaxAttemptsExceeded"
            ]
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "/api/v1",
	Schemes:          []string{},
	Title:            "Ticket API",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
