basePath: /api/v1
definitions:
  ticket-api_internal_dto.ChatMessageDTO:
    properties:
      attachments:
        items:
          type: string
        type: array
      createdAt:
        type: string
      id:
        type: string
      message:
        type: string
      senderId:
        type: integer
      updatedAt:
        type: string
    type: object
  ticket-api_internal_dto.TicketCreateRequest:
    properties:
      attachments:
        items:
          type: string
        type: array
      body:
        description: First message for the ticket (instead of Body/Attachments in
          Ticket)
        type: string
      title:
        type: string
      type:
        type: integer
      userId:
        type: integer
    required:
    - body
    - title
    - type
    - userId
    type: object
  ticket-api_internal_dto.TicketIDResponse:
    properties:
      id:
        type: string
    type: object
  ticket-api_internal_dto.TicketResponse:
    properties:
      chat:
        items:
          $ref: '#/definitions/ticket-api_internal_dto.ChatMessageDTO'
        type: array
      createdAt:
        type: string
      done:
        type: boolean
      id:
        type: string
      priority:
        type: integer
      title:
        type: string
      trackId:
        type: string
      type:
        type: integer
      updatedAt:
        type: string
      userId:
        type: integer
    type: object
  ticket-api_internal_dto.VersionDTO:
    properties:
      apiVersion:
        description: 'JSON: apiVersion'
        type: string
      isCurrent:
        description: 'JSON: isCurrent'
        type: boolean
      notes:
        description: 'JSON: notes'
        type: string
      version:
        description: 'JSON: version'
        type: string
    type: object
info:
  contact: {}
  title: Ticket API
  version: "1.0"
paths:
  /api/{apiVersion}:
    get:
      description: Returns the current version for the given API (v1, v2, etc.)
      parameters:
      - description: API Version
        enum:
        - v1
        - v2
        in: path
        name: apiVersion
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/ticket-api_internal_dto.VersionDTO'
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Get current API version
      tags:
      - Version
  /tickets:
    post:
      consumes:
      - application/json
      description: Creates a new ticket with given data
      parameters:
      - description: Ticket data
        in: body
        name: ticket
        required: true
        schema:
          $ref: '#/definitions/ticket-api_internal_dto.TicketCreateRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/ticket-api_internal_dto.TicketIDResponse'
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Create a new ticket
      tags:
      - Ticket
  /tickets/{id}:
    get:
      description: Returns a ticket by its ID
      parameters:
      - description: Ticket ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/ticket-api_internal_dto.TicketResponse'
        "404":
          description: Not Found
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Get ticket by ID
      tags:
      - Ticket
swagger: "2.0"
