definitions:
  ticket-api_internal_dto.VersionDTO:
    properties:
      apiVersion:
        description: 'JSON: apiVersion'
        type: string
      isCurrent:
        description: 'JSON: isCurrent'
        type: boolean
      notes:
        description: 'JSON: notes'
        type: string
      version:
        description: 'JSON: version'
        type: string
    type: object
info:
  contact: {}
paths:
  /api/{apiVersion}:
    get:
      description: Returns the current version for the given API (v1, v2, etc.)
      parameters:
      - description: API Version
        enum:
        - v1
        - v2
        in: path
        name: apiVersion
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/ticket-api_internal_dto.VersionDTO'
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Get current API version
      tags:
      - Version
swagger: "2.0"
