// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package sms_types

import (
	"context"
)

const getAllSMSTypes = `-- name: GetAllSMSTypes :many
SELECT id, title, description, created_at, updated_at, deleted_at FROM sms_types
WHERE deleted_at IS NULL
ORDER BY id ASC
`

func (q *Queries) GetAllSMSTypes(ctx context.Context) ([]SmsType, error) {
	rows, err := q.db.QueryContext(ctx, getAllSMSTypes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SmsType
	for rows.Next() {
		var i SmsType
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSMSTypeByTitle = `-- name: GetSMSTypeByTitle :one
SELECT id, title, description, created_at, updated_at, deleted_at FROM sms_types
WHERE title = ? AND deleted_at IS NULL
`

func (q *Queries) GetSMSTypeByTitle(ctx context.Context, title string) (SmsType, error) {
	row := q.db.QueryRowContext(ctx, getSMSTypeByTitle, title)
	var i SmsType
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
