// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package users

import (
	"database/sql"
)

type User struct {
	ID           int64
	Username     string
	Password     sql.NullString
	DepartmentID int64
	CreatedAt    string
	UpdatedAt    string
	Status       int64
	Deleted      int64
}
