// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package users

import (
	"context"
)

const checkUserByID = `-- name: CheckUserByID :one
SELECT count(id) exist_of_id FROM users
WHERE deleted = 0
AND status != 0
AND id = ?
`

func (q *Queries) CheckUserByID(ctx context.Context, id int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, checkUserByID, id)
	var exist_of_id int64
	err := row.Scan(&exist_of_id)
	return exist_of_id, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (username, department_id) VALUES (?, ?) RETURNING id
`

type CreateUserParams struct {
	Username     string
	DepartmentID int64
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, createUser, arg.Username, arg.DepartmentID)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const getUser = `-- name: GetUser :one
SELECT u.id, u.username, u.department_id, u.created_at, u.updated_at, u.status, u.deleted
FROM users u
WHERE u.id = ? AND u.deleted = 0
`

type GetUserRow struct {
	ID           int64
	Username     string
	DepartmentID int64
	CreatedAt    string
	UpdatedAt    string
	Status       int64
	Deleted      int64
}

func (q *Queries) GetUser(ctx context.Context, id int64) (GetUserRow, error) {
	row := q.db.QueryRowContext(ctx, getUser, id)
	var i GetUserRow
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.DepartmentID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Status,
		&i.Deleted,
	)
	return i, err
}

const getUserByUsername = `-- name: GetUserByUsername :one
SELECT id FROM users
WHERE deleted = 0
AND status != 0
AND username = ?
`

func (q *Queries) GetUserByUsername(ctx context.Context, username string) (int64, error) {
	row := q.db.QueryRowContext(ctx, getUserByUsername, username)
	var id int64
	err := row.Scan(&id)
	return id, err
}
