// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package users

import (
	"context"
	"database/sql"
	"strings"
)

const checkUserByID = `-- name: CheckUserByID :one
SELECT count(id) exist_of_id FROM users
WHERE deleted = 0
AND status != 0
AND id = ?
`

func (q *Queries) CheckUserByID(ctx context.Context, id int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, checkUserByID, id)
	var exist_of_id int64
	err := row.Scan(&exist_of_id)
	return exist_of_id, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (username, department_id) VALUES (?, ?) RETURNING id
`

type CreateUserParams struct {
	Username     string
	DepartmentID int64
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, createUser, arg.Username, arg.DepartmentID)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const createUserWithPassword = `-- name: CreateUserWithPassword :one
INSERT INTO users (username, password, department_id) VALUES (?, ?, ?) RETURNING id
`

type CreateUserWithPasswordParams struct {
	Username     string
	Password     sql.NullString
	DepartmentID int64
}

func (q *Queries) CreateUserWithPassword(ctx context.Context, arg CreateUserWithPasswordParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, createUserWithPassword, arg.Username, arg.Password, arg.DepartmentID)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, username, password, department_id, created_at, updated_at, status, deleted FROM users
WHERE id = ? 
AND deleted = 0 
AND status != 0
`

func (q *Queries) GetUserByID(ctx context.Context, id int64) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Password,
		&i.DepartmentID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Status,
		&i.Deleted,
	)
	return i, err
}

const getUserByUsername = `-- name: GetUserByUsername :one
SELECT id, username, password, department_id, created_at, updated_at, status, deleted FROM users
WHERE deleted = 0
AND status != 0
AND username = ?
`

func (q *Queries) GetUserByUsername(ctx context.Context, username string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByUsername, username)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Password,
		&i.DepartmentID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Status,
		&i.Deleted,
	)
	return i, err
}

const getUsersByIDs = `-- name: GetUsersByIDs :many
SELECT id, username, password, department_id, created_at, updated_at, status, deleted FROM users
WHERE id IN (/*SLICE:ids*/?)
AND deleted = 0 
AND status != 0
`

func (q *Queries) GetUsersByIDs(ctx context.Context, ids []int64) ([]User, error) {
	query := getUsersByIDs
	var queryParams []interface{}
	if len(ids) > 0 {
		for _, v := range ids {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:ids*/?", strings.Repeat(",?", len(ids))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:ids*/?", "NULL", 1)
	}
	rows, err := q.db.QueryContext(ctx, query, queryParams...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.Password,
			&i.DepartmentID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Status,
			&i.Deleted,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
